trigger: 
  paths:
    include:
      - app/store-front/**
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: k8s-common  
  - name: serviceName 
    value: 'store-front'
  - name: artifactName 
    value: 'storehelmchart'
  - name: imageTag
    value: $(Build.BuildId)
  - name: imageName
    value: 'store-front'

stages:
  - stage: Build
    displayName: Docker Build and Push
    jobs:
      - job: BuildPublishDockerImages
        displayName: Build nad push Docker Images
        steps:
          - template: appTemplates/build.yml
            parameters:
              acrServiceConnection: $(acrServiceConnection)
              imageName: $(imageName)
              dockerFilePath: '$(Build.sourcesdirectory)/app/store-front/Dockerfile'
              tag: $(imageTag)
          
          - task: PublishPipelineArtifact@1
            displayName: Publish Manifest
            inputs:
              targetPath: "$(Build.SourcesDirectory)/$(artifactName)"
              artifact: $(artifactName)